### ISSUE TITLE
Check bài

### ISSUE THREAD

**Issue by HaiYenPham** [doanvu2000/doanvu2000.github.io#1]
https://github.com/doanvu2000/doanvu2000.github.io/blob/5abb8b6be423fd7dd62ec22957511fc92ff69b39/index.html#L99

bài của em ok rùi nhé! phần chia div  này khá quan trọng nên cần nắm kỹ nha!
cố gắng duy trì và phát huy ở các buổi sau nhé!
<3 Thân ái và Quyết thắng <3

**Comment by doanvu2000** [comment]
hi vâng ạ, bài khó quá em làm mãi mới ra huhu
