### ISSUE TITLE
check btvn 2

### ISSUE THREAD

**Issue by HaiYenPham** [doanvu2000/doanvu2000.github.io#2]
https://github.com/doanvu2000/doanvu2000.github.io/blob/89641f4a23670bcbdaf715bac0a19029775df4e6/Day_03/index.html#L4

ok rồi em nhé! 
màu mè giỏi thế này ai dạy được nữa :v

**Comment by doanvu2000** [comment]
sao không có thả buồn cái issues chị nhỉ :( oh noooooooooooooooooooooooooooooo
