### ISSUE TITLE
check bài 3

### ISSUE THREAD

**Issue by HaiYenPham** [doanvu2000/doanvu2000.github.io#3]
https://github.com/doanvu2000/doanvu2000.github.io/blob/fa0aa61289af6fa24ce4dafd0b88acb558992e19/index.html#L9
bài tuần này được rồi em nhé!
phần này sẽ có trong bài kiểm tra trên lớp nên nhớ học kĩ nha!
Thân ái và quyết thắng!

**Comment by doanvu2000** [comment]
hihi em copy bài thằng Đức đấy <3
